# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Featured
    url: /#featured
    weight: 11
  - name: Awards
    url: /#awards
    weight: 12
  - name: Publications
    url: /#papers
    weight: 13
  - name: Personal Projects
    url: /#projects
    weight: 30
